/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenaltiesGUI.java
 *
 * Created on Dec 17, 2011, 10:52:13 PM
 */

package org.scouting.gui;

import org.scouting.filer.FileScanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * @author aoneill
 * @note Made by the Netbeans built-in GUI creator
 */
public class CommentsGUI extends javax.swing.JFrame
{
    private String[] tableHeader = {"Team Number"};
    private int teamCount;
    private String commentDir;
    private String TEAM_LIST_NAME = "TeamList";
    private String DEFAULT_COMMENT_FILE_HEADER = "# Comments #\n";


    /** Creates new form PenaltiesGUI */
    public CommentsGUI()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBox = new javax.swing.JComboBox();
        textScrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        tableLabel = new javax.swing.JLabel();
        comboLabel = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        teamTable = new javax.swing.JTable();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setResizable(false);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        textScrollPane.setViewportView(textArea);

        tableLabel.setText("Teams With Comments");

        comboLabel.setText("Comments For");

        teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teams"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(teamTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tableScrollPane, 0, 0, Short.MAX_VALUE)
                    .add(tableLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 189, Short.MAX_VALUE)
                        .add(comboLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(comboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(textScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tableLabel)
                    .add(comboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(comboLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(textScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .add(tableScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        setCommentsBox(comboBox.getSelectedItem().toString(), commentDir);
    }//GEN-LAST:event_comboBoxActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommentsGUI().setVisible(true);
            }
        });
    }
    
    private void setTeamList(String[] data)
    {
        String[][] list = new String[data.length][1];
        for(int i = 0; i < data.length; i++)
        {
            list[i][0] = data[i];
        }

        teamTable.setModel(new DefaultTableModel(list, tableHeader));
    }

    public void setComments(String[][] allData)
    {
        String[] teamList = extractTeamSequence(allData, teamCount);
        String[] commentHolders = getTeamWithComments(commentDir, teamList);
        setTeamList(commentHolders);
        setComboBox(commentHolders);

        try {
            setCommentsBox(comboBox.getSelectedItem().toString(), commentDir);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    private void setCommentsBox(String teamName, String commentDirPath)
    {
        String teamFileName = teamName + "-Comments.txt";

        FileScanner teamReader = new FileScanner();
        teamReader.openFile(commentDirPath, teamFileName);

        String commentData = "";
        while(teamReader.hasNextEntry())
        {
            commentData = commentData + teamReader.getNextLine() + "\n";
        }

        textArea.setText(commentData);
    }

    private void setComboBox(String[] data)
    {
        comboBox.setModel(new DefaultComboBoxModel(data));
    }

    public void setTeamCount(int num)
    {
        teamCount = num;
    }

    public void setCommentDir(String path)
    {
        commentDir = path;
    }

    public String[] extractTeamSequence(String data[][], int length)
    {
        String[] result = new String[length];
        for(int i = 0; i < length; i++)
        {
            result[i] = data[i][0];
        }

        return result;
    }

    public String[] getTeamWithComments(String commentDirPath, String[] teamList)
    {
        FileScanner teamFileScanner = new FileScanner();
        
        int count = 0;
        for(int i = 0; i < teamList.length; i++)
        {
            teamFileScanner.openFile(commentDirPath, teamList[i] + "-Comments.txt");

            String totalComments = "";
            while(teamFileScanner.hasNextEntry())
            {
                totalComments = totalComments + teamFileScanner.getNextLine() + "\n";
            }

            if(!totalComments.equals(DEFAULT_COMMENT_FILE_HEADER))
            {
                count++;
            }
        }

        String[] result = new String[count];

        count = 0;
        for(int i = 0; i < teamList.length; i++)
        {
            teamFileScanner.openFile(commentDirPath, teamList[i] + "-Comments.txt");

            String totalComments = "";
            while(teamFileScanner.hasNextEntry())
            {
                totalComments = totalComments + teamFileScanner.getNextLine() + "\n";
            }

            if(!totalComments.equals(DEFAULT_COMMENT_FILE_HEADER))
            {
                result[count] = teamList[i];
                count++;
            }
        }

        return result;
    }

    public String[] findCommentHolders(String commentDirPath)
    {
        String[] result;

        int count = 0;
        boolean filesRemain = false;
        while(!filesRemain)
        {
            
        }

        System.out.println("Found " + count + " valid Comment holder(s) of " + teamCount + " valid teams");

        result = new String[count];

        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel comboLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable teamTable;
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textScrollPane;
    // End of variables declaration//GEN-END:variables

}
