/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenaltiesGUI.java
 *
 * Created on Dec 17, 2011, 10:52:13 PM
 */

package org.scouting.gui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * @author aoneill
 * @note Made by the Netbeans built-in GUI creator
 */
public class PenaltiesGUI extends javax.swing.JFrame
{
    private String teamNameString = "Team Number";
    private String headerDataSeparator = "-----------";
    public String[][] allData;
    public String[] tableHeader = {"Team Number"};
    private int teamCount;
    private String penaltiesBoxHeader = "- Penalties -";

    private PenaltiesGUI() {}

    /** Creates new form PenaltiesGUI */
    public PenaltiesGUI(int teamCount, String allData[][])
    {
        initComponents();

        this.teamCount = teamCount;
        this.allData = allData;

        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textScrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        tableLabel = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        teamTable = new javax.swing.JTable();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setResizable(false);

        textArea.setColumns(20);
        textArea.setRows(5);
        textScrollPane.setViewportView(textArea);

        tableLabel.setText("Teams With Penalties");

        teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teams"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(teamTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tableLabel)
                    .add(tableScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(textScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(tableLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init()
    {
        String list[] = extractTeamSequence(allData, teamCount);
        list = removeNull(list);

        try
        {
            setTeamList(list);
            setExpandedPenalties(allData, list[0], teamCount);

            setVisible(true);
        }
        catch(Exception e)
        {
            ErrorGUI eGUI = new ErrorGUI("No teams with penalties!", ErrorGUI.ERROR_LOW);
            setVisible(false);
        }
    }

    public void setTeamList(String[] data)
    {
        String[][] list = new String[data.length][1];
        for(int i = 0; i < data.length; i++)
        {
            list[i][0] = data[i];
        }

        teamTable.setModel(new DefaultTableModel(list, tableHeader));
    }

    public void setExpandedPenalties(String data[][], String currentTeam, int teamCount)
    {
        String extractedPenalties = "";

        for(int i = 0; i < teamCount; i++)
        {
            if(data[i][0].equals(currentTeam))
            {
                extractedPenalties = data[i][6];
            }
        }

        textArea.setText(penaltiesBoxHeader + "\n");

        extractedPenalties = extractedPenalties.replaceAll(":", "\n");

        textArea.append(extractedPenalties);

    }

    public String[] extractTeamSequence(String data[][], int length)
    {
        String[] result = new String[length];
        for(int i = 0; i < length; i++)
        {
            result[i] = data[i][0];
        }

        return result;
    }

    public String[] removeNull(String[] data)
    {
        String[] result;

        int count = 0;
        for(int i = 0; i < data.length; i++)
        {
            if(Integer.parseInt(data[i]) != 0)
            {
                count++;
            }
        }

        System.out.println("Found " + count + " valid Penalty holder(s) of " + teamCount + " valid teams");

        result = new String[count];

        count = 0;
        for(int i = 0; i < data.length; i++)
        {
            if(Integer.parseInt(data[i]) != 0)
            {
                result[count] = data[i];
                count++;
            }
        }

        return result;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenaltiesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable teamTable;
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textScrollPane;
    // End of variables declaration//GEN-END:variables

}
